### ISSUE TITLE
Generated decode method for variable fields does not support optional fields correctly

### ISSUE THREAD

**Issue by gendusoa** [jaustoolset/jaustoolset#10]
Generated code for JSIDL variable_fields includes the optional wrapper in the generateInstanceEncodeMethod(), but does not include it in generateInstanceDecodeMethod(). This leads to decoding errors with the AS6009A mobility services. The missing code is in org/jts/codegenerator/VariableFieldGenerator.java around line 1255 in master as of today.

**Comment by dvmartin999** [comment]
Fixed
