### ISSUE TITLE
scons fails to build templates

### ISSUE THREAD

**Issue by stharding** [jaustoolset/jaustoolset#5]
In the directory: `jaustoolset/GUI/templates/Common`
if you run `scons` the following error is printed:

```
scons: *** Import of non-existent variable ''env''
File "/home/developer/repos/jaustoolset/GUI/templates/Common/Sconstruct", line 7, in <module>
```

this happens on Debian and OSX

**Comment by dvmartin999** [comment]
The templates/Common directory is not intended to be built stand-alone.  Rather, Common/Sconstruct will be called during the build of a generated JAUS components (or the node manager).  That calling/owning component Sconstruct sets up the applicable 'env' environment and exports it.
