### ISSUE TITLE
Config File error logging

### ISSUE THREAD

**Issue by chriszeh-DCS** [jaustoolset/jaustoolset#51]
When the configuration file is not found for the node manager (in the RunJuniorRTE method of the JuniorRTE class), it informs the user via the JrError macro.  The problem is that the logging level is read from the configuration file and is initialized to none.  Some hapless soul (like myself) could easily miss the fact that the configuration file was not being read because that message is not being displayed.

**Comment by dvmartin999** [comment]
Fixed on PR #53
