### ISSUE TITLE
ReliableDelivery flag (JAUS ACK/NACK) not working

### ISSUE THREAD

**Issue by micah-boswell-gdms** [jaustoolset/jaustoolset#6]
The JTS "generated" C++ code does not call the Jr interface functions correctly, and this results in several issues, the most important to me being the failure of the ReliableDelivery or ACK/NACK protocol. Instead of passing the ReliableDelivery flag through from the Send_1_1 interface, the flag is ignored and has no effect. (Strangely, the flag does get set anyway on broadcast messages, which is taking advantage of implementation-specific behavior on the other end because the spec clearly says that's not defined behavior.) I do have a patch which addresses this issue and I'm working on a pull request.

**Comment by micah-boswell-gdms** [comment]
The code in question is in  [jaustoolset/GUI/templates/Common/src/Transport/JausTransport.cpp](https://github.com/dvmartin999/jaustoolset/blob/master/GUI/templates/Common/src/Transport/JausTransport.cpp) , in case you're not familiar with it.

**Comment by micah-boswell-aquabotix** [comment]
Sorry, due to job change the pull request/patch is no longer in the works.
