### ISSUE TITLE
Sample code does not run

### ISSUE THREAD

**Issue by covertcorvid** [jaustoolset/jaustoolset#8]
Following the tutorial program in chapter 7 of the User Guide, PingComponent_120 fails to execute with the error "error while loading shared libraries: libPingServer.so: cannot open shared object file: No such file or directory"
Manually soft-linking to the .so files from /usr/lib is a quick workaround.

This is on a VM running CentOS 6.8

**Comment by dvmartin999** [comment]
Fixed under PR37
